setting =  [{'MC': 'root_MCJNT', 'RH': 'allOffset_ctrl', 'const': 'parentConstraint[mo]'},
            {'MC': 'hip_MCJNT', 'RH': 'hip_ctrl', 'const': 'orientConstraint[mo]'},
            {'MC': 'waist_MCJNT', 'RH': 'waist_ctrl', 'const': 'orientConstraint[mo]'},
            {'MC': 'thigh_MCJNT_R','RH': 'secLegPV_ctrl_R','const': 'parentConstraint[mo]'},
            {'MC': 'spineA_MCJNT', 'RH': 'spineA_ctrl', 'const': 'orientConstraint[mo]'},
            {'MC': 'thigh_MCJNT_L','RH': 'secLegPV_ctrl_L','const': 'parentConstraint[mo]'},
            {'MC': 'spineB_MCJNT', 'RH': 'spineB_ctrl', 'const': 'orientConstraint[mo]'},
            {'MC': 'kneeA_MCJNT_L', 'RH': 'leg_ctrl_L', 'const': 'parentConstraint[mo]'},
            {'MC': 'kneeA_MCJNT_R', 'RH': 'leg_ctrl_R', 'const': 'parentConstraint[mo]'},
            {'MC': 'ankle_MCJNT_R', 'RH': 'ankle_ctrl_R', 'const': 'orientConstraint[mo]'},
            {'MC': 'ankle_MCJNT_L', 'RH': 'ankle_ctrl_L', 'const': 'orientConstraint[mo]'},
            {'MC': 'chest_MCJNT', 'RH': 'chest_ctrl', 'const': 'orientConstraint[mo]'},
            {'MC': 'collar_MCJNT', 'RH': 'collar_ctrl', 'const': 'orientConstraint[mo]'},
            {'MC': 'ball_MCJNT_L', 'RH': 'toe_ctrl_L', 'const': 'orientConstraint[mo]'},
            {'MC': 'ball_MCJNT_R', 'RH': 'toe_ctrl_R', 'const': 'orientConstraint[mo]'},
            {'MC': 'clavicle_MCJNT_L','RH': 'clavicle_ctrl_L','const': 'orientConstraint[mo]'},
            {'MC': 'clavicle_MCJNT_R','RH': 'clavicle_ctrl_R','const': 'orientConstraint[mo]'},
            {'MC': 'neck_MCJNT', 'RH': 'neck_ctrl', 'const': 'orientConstraint[mo]'},
            {'MC': 'shoulderA_MCJNT_R','RH': 'secArmPV_ctrl_R','const': 'parentConstraint[mo]'},
            {'MC': 'shoulderA_MCJNT_L','RH': 'secArmPV_ctrl_L','const': 'parentConstraint[mo]'},
            {'MC': 'face_MCJNT', 'RH': 'face_ctrl', 'const': 'orientConstraint[mo]'},
            {'MC': 'elbowA_MCJNT_L', 'RH': 'arm_ctrl_L', 'const': 'parentConstraint[mo]'},
            {'MC': 'elbowA_MCJNT_R', 'RH': 'arm_ctrl_R', 'const': 'parentConstraint[mo]'},
            {'MC': 'wrist_MCJNT_L', 'RH': 'wrist_ctrl_L', 'const': 'orientConstraint[mo]'},
            {'MC': 'wrist_MCJNT_R', 'RH': 'wrist_ctrl_R', 'const': 'orientConstraint[mo]'},
            {"MC": "handB_MCJNT_R",     "RH":"handB_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "thumbA_MCJNT_R",    "RH":"thumbA_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "thumbB_MCJNT_R",        "RH":"thumbB_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "thumbC_MCJNT_R",        "RH":"thumbC_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "thumbD_MCJNT_R",        "RH":"thumbD_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "foreFingerA_MCJNT_R",   "RH":"foreA_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "foreFingerB_MCJNT_R",   "RH":"foreB_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "foreFingerC_MCJNT_R",   "RH":"foreC_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "middleFingerA_MCJNT_R", "RH":"middleA_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "middleFingerB_MCJNT_R", "RH":"middleB_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "middleFingerC_MCJNT_R", "RH":"middleC_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "ringFingerA_MCJNT_R",   "RH":"ringA_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "ringFingerB_MCJNT_R",   "RH":"ringB_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "ringFingerC_MCJNT_R",   "RH":"ringC_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "littleFingerA_MCJNT_R", "RH":"littleA_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "littleFingerB_MCJNT_R", "RH":"littleB_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "littleFingerC_MCJNT_R", "RH":"littleC_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "littleFingerD_MCJNT_R", "RH":"littleD_ctrl_R", "const":"orientConstraint[mo]"},
            {"MC": "handB_MCJNT_L",     "RH":"handB_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "thumbA_MCJNT_L",    "RH":"thumbA_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "thumbB_MCJNT_L",        "RH":"thumbB_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "thumbC_MCJNT_L",        "RH":"thumbC_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "thumbD_MCJNT_L",        "RH":"thumbD_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "foreFingerA_MCJNT_L",   "RH":"foreA_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "foreFingerB_MCJNT_L",   "RH":"foreB_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "foreFingerC_MCJNT_L",   "RH":"foreC_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "middleFingerA_MCJNT_L", "RH":"middleA_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "middleFingerB_MCJNT_L", "RH":"middleB_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "middleFingerC_MCJNT_L", "RH":"middleC_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "ringFingerA_MCJNT_L",   "RH":"ringA_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "ringFingerB_MCJNT_L",   "RH":"ringB_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "ringFingerC_MCJNT_L",   "RH":"ringC_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "littleFingerA_MCJNT_L", "RH":"littleA_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "littleFingerB_MCJNT_L", "RH":"littleB_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "littleFingerC_MCJNT_L", "RH":"littleC_ctrl_L", "const":"orientConstraint[mo]"},
            {"MC": "littleFingerD_MCJNT_L", "RH":"littleD_ctrl_L", "const":"orientConstraint[mo]"},
]
root = "root_MCJNT"

other = "allWorld_ctrl"
